auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “WangYu's Blog”
title: WangYu's Blog
description: Something about chaingForever.
url: http://chaingForever.github.io
feed: /atom.xml
author_info: <a href="http://chaingForever.github.io/">chaingForever</a>
