auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “wangyu's Blog”
title: wangyu's blog
description: Everything about wangyu.
url: http://chaingForever.github.io
feed: /atom.xml
author_info: <a href="http://chaingForever.github.io/">chaingForever</a>
